### ISSUE TITLE
ATlauncher not installing cucumber during installation

### ISSUE THREAD

**Issue by mike9863** [AMPZNetwork/All-The-Forge-6#2]
**Describe the bug**
title

**To Reproduce**
install pack using ATlauncher and start pack.

**Screenshots**

**Crash Report**
Please paste your crash report (pastebin links are preferred.

**Desktop :windows

**Additional context**
Was able to fix by manually adding cucumber to pack

**Comment by LabsZero** [comment]
Thank you for the report, the issue has now been resolved and this issue is now closed. if you come across any more issue feel free to open more tickets.
