### ISSUE TITLE
[ATF6] [MC1.16.5 1.9.0-Beta-10] (Plant?) Item drops are limited to 16

### ISSUE THREAD

**Issue by CyberSer69** [AMPZNetwork/All-The-Forge-6#4]
I recently noticed that when I destroy trees using the Falling Tree mod or normally destroy bamboo or sugar cane in large quantities (definitely more than 16 item-worth) it only drops 16 of them regardless of how much I harvest. I noticed I don't get much wood from cutting down trees when I first started the freshly instanced modpack and for a while, I thought it was intended but after some time I found it pretty annoying.

1. Plant a lot of bamboo/sugar cane or a big tree
2. Harvest the first ones by hand or the tree with an axe (so that the Falling Tree mod works)
3. Get only 16 items or very few items (bamboo/sugar cane or logs for the trees)

While destroying large quantities of those items you should get a lot of drops from them. I added some mods on my own, though the bug happened beforehand as well.

The bug doesn't include a crash, although here is the paste from the ATLauncher log:
[https://paste.atlauncher.com/view/a4e5f562-ab28-4c38-8720-9b626650d8fe](https://paste.atlauncher.com/view/a4e5f562-ab28-4c38-8720-9b626650d8fe)

 - OS: Windows 10
 - All The Forge 6 Version 1.9.0-Beta-10
 - Platform: ATLauncher
 - Extra mods added by you: Optifine, CreativeCore (dependency for AmbientSounds), AmbientSounds

**Comment by LabsZero** [comment]
Fixed in the upcoming update V1.10.0 (Beta 11)
