### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IHateThisWebservice** [AMPZNetwork/All-The-Forge-6#6]
**Describe the bug**

**To Reproduce**
1. Go in game and make a tinkers crafting station
2. The sort button is in the middle of the crafting table and very annoying

**Expected behavior**
A button not to be in the middle of crafting

**Screenshots**
https://shortnme.cc/tDXEo

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - All The Forge 6 Version Latest
 - Platform at launcher
 - Extra mods added by you Optifine

**Comment by LabsZero** [comment]
Thank you for your report, this issue has been fixed in the next patch.
