### ISSUE TITLE
Curseforge Beta Incompatibility: 1.15.0 Missing

### ISSUE THREAD

**Issue by Artzfall** [AMPZNetwork/All-The-Forge-6#7]
I'm trying a bunch of modpacks, and I downloaded this pack, which has a critical issue on Curseforge Beta/Overwolf. If 1.15.0 is downloaded, nothing will be installed, so it is necessary to force the profile to rollback to 1.14.0 in order for it to have any content. If possible, please fix this. Thanks!

**Comment by LabsZero** [comment]
Thank you for your report i have published v1.15.1 to curseforge to fix this issue.
